### ISSUE TITLE
Titanium Feature Not installing on Eclipse

### ISSUE THREAD

**Issue by rkommine** [eclipse/titan.EclipsePlug-ins#1]
Hi,

I am installing the TITAN on windows 7 using cygwin. After Installation of TITAN core I tried installing the TITAN eclipse plugin's. I did the following steps:

1. Installed Apache POI & ANTLR run time.
2. Copied the edu.uci.ics.jung/*.jar files to eclipse/plugins folder.
3. Copied the org.apache.commons.collections15/*.jar  to eclipse/plugins folder

After this I started installing the eclipse TITAN plugin's TITAN_on_Eclipse_5.4.0.CRL_113_200_5_R4A_20151113-1513.zip.

But I am getting below error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Titanium_Feature 5.4.0.CRL_113_200_5_R4A_20151113-1513 (Titanium.feature.group 5.4.0.CRL_113_200_5_R4A_20151113-1513)
  Missing requirement: Titanium_Feature 5.4.0.CRL_113_200_5_R4A_20151113-1513 (Titanium.feature.group 5.4.0.CRL_113_200_5_R4A_20151113-1513) requires 'edu.uci.ics.jung 0.0.0' but it could not be found

Could anyone please help me to avoid above error for installation?

Thanks in advance.

**Comment by erititan** [comment]
Hi Ramakrishna,

pls. check this forum post:

https://www.eclipse.org/forums/index.php/t/1072422/

There's a detailed explanation there how to install the plug-ins.

Best regards

Elemer

**Comment by rkommine** [comment]
Hi Elemer,

Many thanks for the link. Now I am able to use install the Eclipse plugin's for Titan.

Regards,
Ramakrishna
