### ISSUE TITLE
The version of the compiler used: could not be determined

### ISSUE THREAD

**Issue by rkommine** [eclipse/titan.EclipsePlug-ins#3]
Hi,

I have Installed the titan on cygwin.

```
 $ compiler -v
TTCN-3 and ASN.1 Compiler for the TTCN-3 Test Executor
Product number: CRL 113 200/5 R4D
Build date: Apr  7 2016 23:58:59
Compiled with: GCC 5.3.0

Copyright (c) 2000-2016 Ericsson Telecom AB
```
After this I installed titan eclipse plugin's as mentioned in eclipse installation guide. All the plugin's installation is also successful.  Now when I go to eclipse & check Titan Prefrences I am getting below error.

The version of the compiler used: could not be determined

Could you please help how to fix the issue?

Regards,
Ramakrishna

**Comment by KristofSzabados** [comment]
Hi Ramakrishna,

When you go to the Titan Preferences page, is the path to the compiler set?
You can also check the debug console for information. That console shows the exact command executed in the command line and the answer received on it.

Best Regards
Kristof

**Comment by rkommine** [comment]
Hi Kristof,

I have set the compiler path:

`C:\cygwin\home\rkommine\titan.core\Install`

In the debug console I can see only the following message:

`**************************************************************
2016-04-09_20:14:21: starting to build Testing
**************************************************************
sh -c make dep  
execution failed
**************************************************************
2016-04-09_20:14:23: starting to build Testing
**************************************************************
sh -c make dep  
execution failed`

Also error log shows the below message:

`eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

org.eclipse.titan.common
Error
Sat Apr 09 20:14:23 IST 2016
Cannot run program "sh" (in directory "C:\Users\rkommine\workspace\Testing\bin"): CreateProcess error=2, The system cannot find the file specified

java.io.IOException: Cannot run program "sh" (in directory "C:\Users\rkommine\workspace\Testing\bin"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.eclipse.titan.designer.core.TITANJob.runInWorkspace(TITANJob.java:285)
	at org.eclipse.titan.designer.core.TITANBuilder.build(TITANBuilder.java:1136)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

`
I have installed the TITAN in the below location:

`C:\cygwin\home\rkommine\titan.core\Install`

The following Environment variables are created:

`TTCN3_DIR=/home/rkommine/titan.core/Install
LD_LIBRARY_PATH=/home/rkommine/titan.core/Install/lib:/home/rkommine/titan.core/Install/lib:/home/rkommine/titan.core/Install/lib`

Regards,
Ramakrishna

**Comment by KristofSzabados** [comment]
Hi Ramakrishna,

I believe your windows might not be set up correctly just yet :(
According to the error message the eclipse plugin is not able to invoke the sh command.
The designer does this by simply trying to execute it as a normal windows command ... but windows itself might not be able to find it.

To see if this is the case you could open up a normal windows command prompt (for example in the start menu execute the command "cmd"), and in the window that comes up try to execute the command "sh". If successful this should give you a bash shell ... but in your case I believe you will receive an error message saying that windows could not find the "sh" command.

To solve the issue, you might need to add the bin folder of your cygwin installation to the "Path" environmental variable of windows, yourself, by hand.

**Comment by rkommine** [comment]
Hi Kristof,

Thanks for the response. I tried sh command on a command prompt it is not recognized.
So I added the %cygwin%;%cygwin%\bin; at teh start of the path in windows. Now the Build is successfull & Titan compiler version is shown.

But I am getting this error log:

`!SESSION 2016-04-09 22:17:17.096 -----------------------------------------------
eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.titan.common 4 0 2016-04-09 22:17:50.805
!MESSAGE The path:`' could not be converted`

I saw a post in eclipse titan community forum.
https://www.eclipse.org/forums/index.php/t/1075026/

Similar error is reported. Is this issue with Titan eclipse plugin or titan core itself?

Regards,
Ramakrishna

**Comment by KristofSzabados** [comment]
Hi Ramakrishna,

I don't really know where this is coming from, The designer tries to convert the path of something that is not there.
Could you please check the ErrorLog view and the designer's debug console output?
(maybe that way we can figure out what went wrong)

**Comment by KristofSzabados** [comment]
Hi Ramakrishna,

I believe the error might have been the result of having a single space in the parh of the compiler at some time.
I have committed a fix in the sourcecode that fixes that situation just now.

**Comment by rkommine** [comment]
Hi Kristof,

Many thanks for the response. I have removed complete titan installation & cygwin. I will reinstall properly again & let you know if I face the issue again.

Regards,
Ramakrishna
