### ISSUE TITLE
Installation and Setup Issues

### ISSUE THREAD

**Issue by pauldavidgilligan** [eclipse/titan.EclipsePlug-ins#97]
The dependencies for the ant build are not clear how is this project built?

So far I have got eclipse_juno_java7_linux_x64 setup with JAVA 7 and I get error:

```java
import org.antlr.v4.runtime.misc.Nullable;
    [javac]                                 ^
    [javac]   symbol:   class Nullable
    [javac]   location: package org.antlr.v4.runtime.misc
    [javac] /home/devops/Downloads/titan.EclipsePlug-ins-master/org.eclipse.titan.common/src/org/eclipse/titan/common/parsers/TitanListener.java:35: error: cannot find symbol
    [javac] 	public void syntaxError(final @NotNull Recognizer<?, ?> recognizer, final @Nullable Object offendingSymbol, final int line, final int charPositionInLine,
```

**Comment by pauldavidgilligan** [comment]
I would like to compile the eclipse plugin with:

a) JAVA 7 or 8 minimum
b) Eclipse Mars or Neon minimum

Testing with ant 1.9.3 current release and antlr-4.5.3-complete.jar

Some simple steps would be appreciated

**Comment by pauldavidgilligan** [comment]
Testing on Ubuntu 14 with:

```bash
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install aptitude
sudo aptitude install git
sudo aptitude install ant
sudo aptitude install ant-contrib

export ANT_HOME=/usr/share/ant/
export JAVA_HOME=/opt/jdk1.7.0_79
```

**Comment by erititan** [comment]
Hi Paul,

please try to follow the README file 
https://github.com/eclipse/titan.EclipsePlug-ins/blob/master/README

If any problems,  get stuck etc. let us know.
 
I'd recommend Mars, we did not test it with Neon yet.

Best regards
Elemer

**Comment by erititan** [comment]
BTW, 
pre-built package is available at 
https://projects.eclipse.org/projects/tools.titan/downloads
 
BR Elemer

**Comment by pauldavidgilligan** [comment]
Hi the README needs updating with clear steps on which files to download, how to install commons/juno with eclipse, how to install plugin. Then how download titan, install and setup with eclipse.

**Comment by erititan** [comment]
Hi Paul,

I suggest then you use pre-built packages first ; please check installation guides in the documentation package.
After you get familiar with the environment, it will become easier to build from source.

For Titan dependencies , see also README.linux in https://github.com/eclipse/titan.core
Once you have the command line up and running proceed with the (pre-built) Eclipse plug-ins according to the install guide.

I hope this helps 
Best regards

Elemer

**Comment by pauldavidgilligan** [comment]
same errors on mars 2 and neon

**Comment by alovassy** [comment]
Hi,

Titanium feature needs the following jar files to be installed:

edu.uci.ics.jung/jung-graph-impl-2.0.1.jar
edu.uci.ics.jung/jung-visualization-2.0.1.jar
edu.uci.ics.jung/jung-algorithms-2.0.1.jar
edu.uci.ics.jung/jung-io-2.0.1.jar
org.apache.poi_3.9.0.v201405241750.jar

Please make sure, that these jars are in eclipse/plugins directory.
If these jars are missing from there, copy the jars manually to the eclipse/plugins directory.

Regards
Árpád

**Comment by pauldavidgilligan** [comment]
Contents of your zip are>

```bash
devops@devops-VirtualBox:~/Downloads$ unzip edu.uci.ics.jung.zip
Archive:  edu.uci.ics.jung.zip
   creating: edu.uci.ics.jung/
  inflating: edu.uci.ics.jung/.classpath  
  inflating: edu.uci.ics.jung/.project  
   creating: edu.uci.ics.jung/.settings/
  inflating: edu.uci.ics.jung/.settings/org.eclipse.jdt.core.prefs  
  inflating: edu.uci.ics.jung/build.properties  
  inflating: edu.uci.ics.jung/jung-algorithms-2.0.1.jar  
  inflating: edu.uci.ics.jung/jung-api-2.0.1.jar  
  inflating: edu.uci.ics.jung/jung-graph-impl-2.0.1.jar  
  inflating: edu.uci.ics.jung/jung-io-2.0.1.jar  
  inflating: edu.uci.ics.jung/jung-visualization-2.0.1.jar  
   creating: edu.uci.ics.jung/META-INF/
  inflating: edu.uci.ics.jung/META-INF/MANIFEST.MF  
```
It seems we are missing org.apache.poi_3.9.0.v201405241750.jar ?

**Comment by alovassy** [comment]
Yes, you need the org.apache.poi also,
it is available at Eclipse Orbit
http://download.eclipse.org/tools/orbit/downloads/
http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/ (For Eclipse Neon)

And there is one more dependency of Titanium, I forgot in my last post:
org.apache.commons.collections15/collections-generic-4.01.jar
Download it from http://commons.apache.org/proper/commons-collections/

Regards
Árpád

**Comment by erititan** [comment]
Hi Paul,

commons-collections can be also downloaded from:
https://projects.eclipse.org/projects/tools.titan/download

Please use this one to make sure version is OK.

BR Elemer

**Comment by erititan** [comment]
Hi Paul, 
all the above is described in ch 3 Installing prerequisites of the Eclipse installation guide.

BR 
Elemer

**Comment by erititan** [comment]
I'll close this for now.
